from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


# ============================================================================
# PROJECT ROOT
# ============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]


class Settings(BaseSettings):
    """
    Central configuration for FraudGraph-Agent.

    The project is designed to run locally with:

        LLM              -> Ollama
        Embeddings       -> sentence-transformers
        Vector store     -> FAISS
        Graph database   -> TigerGraph
        Backend          -> FastAPI
        Agent            -> LangGraph

    No paid LLM API is required.

    IMPORTANT:
    This configuration does not contain dataset-specific column names.
    Those must be discovered from the HHGOA README and actual dataset files
    before implementing the ingestion/preprocessing pipeline.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # =========================================================================
    # APPLICATION
    # =========================================================================

    app_name: str = "FraudGraph Agent"

    app_version: str = "0.1.0"

    environment: Literal[
        "development",
        "testing",
        "staging",
        "production",
    ] = "development"

    debug: bool = False

    api_prefix: str = "/api/v1"

    host: str = "0.0.0.0"

    port: int = Field(
        default=8000,
        ge=1,
        le=65535,
    )

    # =========================================================================
    # CORS
    # =========================================================================

    cors_origins: list[str] = Field(
        default_factory=lambda: [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
        ]
    )

    # =========================================================================
    # DATASET
    # =========================================================================

    # Main project data directory.
    data_dir: Path = PROJECT_ROOT / "data"

    # Original HHGOA files.
    #
    # Put the supplied dataset files here.
    raw_data_dir: Path = (
        PROJECT_ROOT / "data" / "raw"
    )

    # Cleaned/transformed data generated by preprocessing.
    processed_data_dir: Path = (
        PROJECT_ROOT / "data" / "processed"
    )

    # Benchmark cases and generated benchmark outputs.
    benchmark_data_dir: Path = (
        PROJECT_ROOT / "data" / "benchmark"
    )

    # Policy, fraud-pattern and regulatory documents.
    documents_dir: Path = (
        PROJECT_ROOT / "data" / "documents"
    )

    # =========================================================================
    # DATA PROCESSING
    # =========================================================================

    # Number of rows processed per batch while reading large CSV/Parquet files.
    #
    # This prevents loading the entire HHGOA dataset into RAM at once.
    dataset_chunk_size: int = Field(
        default=10_000,
        ge=100,
    )

    # Whether preprocessing is allowed to overwrite generated processed files.
    overwrite_processed_data: bool = False

    # =========================================================================
    # TIGERGRAPH
    # =========================================================================

    tigergraph_host: str = ""

    tigergraph_username: str = ""

    tigergraph_password: str = ""

    tigergraph_graph_name: str = ""

    tigergraph_api_token: str = ""

    tigergraph_timeout_seconds: float = Field(
        default=30.0,
        gt=0,
    )

    # =========================================================================
    # TIGERGRAPH MCP
    # =========================================================================

    # MCP is optional during local development but required for the
    # challenge architecture when the TigerGraph MCP integration is enabled.
    tigergraph_mcp_enabled: bool = False

    tigergraph_mcp_url: str = ""

    tigergraph_mcp_timeout_seconds: float = Field(
        default=30.0,
        gt=0,
    )

    # =========================================================================
    # GSQL / GRAPH PROCESSING
    # =========================================================================

    # Directory containing GSQL schema, loading jobs, queries and algorithms.
    tigergraph_gsql_dir: Path = (
        PROJECT_ROOT / "tigergraph"
    )

    tigergraph_schema_dir: Path = (
        PROJECT_ROOT
        / "tigergraph"
        / "schema"
    )

    tigergraph_queries_dir: Path = (
        PROJECT_ROOT
        / "tigergraph"
        / "queries"
    )

    tigergraph_algorithms_dir: Path = (
        PROJECT_ROOT
        / "tigergraph"
        / "algorithms"
    )

    tigergraph_loading_dir: Path = (
        PROJECT_ROOT
        / "tigergraph"
        / "loading"
    )

    # =========================================================================
    # LOCAL LLM
    # =========================================================================

    # Strictly local/free-first.
    #
    # Ollama runs on the developer machine.
    # No API key is required.
    llm_provider: Literal["ollama"] = "ollama"

    # This can be changed depending on available RAM/GPU.
    #
    # Examples:
    #   llama3.1:8b
    #   qwen2.5:7b
    #   gemma3:4b
    #
    # The actual model will be selected based on the machine and benchmark
    # quality after the base system is working.
    llm_model: str = "llama3.1:8b"

    # Default Ollama endpoint.
    llm_base_url: str = "http://localhost:11434"

    llm_temperature: float = Field(
        default=0.0,
        ge=0.0,
        le=2.0,
    )

    llm_timeout_seconds: float = Field(
        default=120.0,
        gt=0,
    )

    # =========================================================================
    # EMBEDDINGS
    # =========================================================================

    # Local embedding model.
    embedding_provider: Literal[
        "sentence_transformers"
    ] = "sentence_transformers"

    embedding_model: str = (
        "sentence-transformers/all-MiniLM-L6-v2"
    )

    embedding_dimension: int = Field(
        default=384,
        ge=1,
    )

    # =========================================================================
    # VECTOR STORE
    # =========================================================================

    # Local FAISS vector index.
    vector_store: Literal["faiss"] = "faiss"

    vector_store_dir: Path = (
        PROJECT_ROOT
        / "data"
        / "processed"
        / "vector_store"
    )

    # =========================================================================
    # DOCUMENT PROCESSING / GRAPHRAG
    # =========================================================================

    graphrag_enabled: bool = True

    graphrag_top_k: int = Field(
        default=10,
        ge=1,
        le=100,
    )

    graphrag_rerank_top_k: int = Field(
        default=5,
        ge=1,
        le=100,
    )

    # Maximum approximate document chunk size before embedding.
    document_chunk_size: int = Field(
        default=1000,
        ge=100,
    )

    document_chunk_overlap: int = Field(
        default=150,
        ge=0,
    )

    # =========================================================================
    # FRAUD INVESTIGATION
    # =========================================================================

    # Maximum number of agent workflow steps for a single investigation.
    agent_max_steps: int = Field(
        default=20,
        ge=1,
        le=100,
    )

    agent_timeout_seconds: float = Field(
        default=300.0,
        gt=0,
    )

    # Human approval is enabled by default.
    agent_enable_human_approval: bool = True

    # =========================================================================
    # EVIDENCE
    # =========================================================================

    # Minimum evidence quality required before an action recommendation
    # can be considered defensible.
    #
    # This is an application-level configuration only.
    # Actual thresholds must be derived from challenge policy documents
    # where applicable.
    evidence_minimum_score: float = Field(
        default=0.60,
        ge=0.0,
        le=1.0,
    )

    # =========================================================================
    # RISK / UNCERTAINTY
    # =========================================================================

    # Risk thresholds are configurable rather than hard-coded throughout
    # the application.
    #
    # These values are starting engineering defaults, NOT claims about
    # HHGOA policy. They must be validated against the supplied policy.
    risk_low_threshold: float = Field(
        default=0.30,
        ge=0.0,
        le=1.0,
    )

    risk_medium_threshold: float = Field(
        default=0.60,
        ge=0.0,
        le=1.0,
    )

    risk_high_threshold: float = Field(
        default=0.85,
        ge=0.0,
        le=1.0,
    )

    uncertainty_threshold: float = Field(
        default=0.40,
        ge=0.0,
        le=1.0,
    )

    # =========================================================================
    # CASE MEMORY
    # =========================================================================

    case_memory_enabled: bool = True

    case_memory_top_k: int = Field(
        default=5,
        ge=1,
        le=50,
    )

    # =========================================================================
    # ACTIONS
    # =========================================================================

    # IMPORTANT:
    # Real external action execution remains disabled by default.
    #
    # The challenge permits mocked/stubbed integrations for actions such as:
    # transaction controls, customer messages, CRM updates, etc.
    allow_action_execution: bool = False

    # Even if action execution is enabled, approval is required unless
    # the policy engine explicitly determines that approval is unnecessary.
    require_approval_for_external_actions: bool = True

    # =========================================================================
    # SAR / REGULATORY REPORTING
    # =========================================================================

    sar_enabled: bool = True

    # SAR generation should be policy-driven.
    # We do not hard-code a regulatory conclusion here.
    sar_require_policy_check: bool = True

    # =========================================================================
    # BENCHMARK
    # =========================================================================

    benchmark_enabled: bool = True

    benchmark_cases_dir: Path = (
        PROJECT_ROOT
        / "data"
        / "benchmark"
        / "cases"
    )

    benchmark_outputs_dir: Path = (
        PROJECT_ROOT
        / "data"
        / "benchmark"
        / "outputs"
    )

    benchmark_max_cases: int = Field(
        default=20,
        ge=1,
    )

    # =========================================================================
    # RUNTIME OUTPUTS
    # =========================================================================

    outputs_dir: Path = (
        PROJECT_ROOT / "outputs"
    )

    investigations_output_dir: Path = (
        PROJECT_ROOT
        / "outputs"
        / "investigations"
    )

    benchmark_output_dir: Path = (
        PROJECT_ROOT
        / "outputs"
        / "benchmark"
    )

    reports_output_dir: Path = (
        PROJECT_ROOT
        / "outputs"
        / "reports"
    )

    # =========================================================================
    # AUTHENTICATION
    # =========================================================================

    # Disabled for initial local development.
    auth_enabled: bool = False

    jwt_secret_key: str = ""

    jwt_algorithm: str = "HS256"

    jwt_access_token_expire_minutes: int = Field(
        default=60,
        ge=1,
    )

    # =========================================================================
    # LOGGING
    # =========================================================================

    log_level: str = "INFO"

    log_json: bool = False

    # =========================================================================
    # API BEHAVIOUR
    # =========================================================================

    request_timeout_seconds: float = Field(
        default=30.0,
        gt=0,
    )

    max_request_body_bytes: int = Field(
        default=5 * 1024 * 1024,
        ge=1024,
    )

    # =========================================================================
    # COMPUTED HELPERS
    # =========================================================================

    @property
    def is_development(self) -> bool:
        return self.environment == "development"

    @property
    def is_testing(self) -> bool:
        return self.environment == "testing"

    @property
    def is_production(self) -> bool:
        return self.environment == "production"

    @property
    def tigergraph_configured(self) -> bool:
        """
        Return True when sufficient TigerGraph configuration exists.
        """

        has_host = bool(self.tigergraph_host)

        has_graph = bool(self.tigergraph_graph_name)

        has_token = bool(self.tigergraph_api_token)

        has_credentials = bool(
            self.tigergraph_username
            and self.tigergraph_password
        )

        return bool(
            has_host
            and has_graph
            and (has_token or has_credentials)
        )

    @property
    def tigergraph_mcp_configured(self) -> bool:
        """
        Return True when TigerGraph MCP is enabled and has an endpoint.
        """

        return bool(
            self.tigergraph_mcp_enabled
            and self.tigergraph_mcp_url
        )

    @property
    def llm_configured(self) -> bool:
        """
        Return True when the local Ollama LLM configuration exists.

        No API key is required.
        """

        return bool(
            self.llm_provider == "ollama"
            and self.llm_model
            and self.llm_base_url
        )

    @property
    def embeddings_configured(self) -> bool:
        """
        Return True when local sentence-transformers embeddings
        are configured.
        """

        return bool(
            self.embedding_provider == "sentence_transformers"
            and self.embedding_model
        )

    @property
    def vector_store_configured(self) -> bool:
        """
        Return True when FAISS is configured.
        """

        return self.vector_store == "faiss"

    # =========================================================================
    # RUNTIME DIRECTORY PREPARATION
    # =========================================================================

    def ensure_runtime_directories(self) -> None:
        """
        Create application-owned directories if they do not exist.

        This does NOT:
            - download the HHGOA dataset
            - create fake transactions
            - create demo cases
            - seed fake customers
            - generate fake graph data

        It only creates empty application directories.
        """

        directories = (
            self.raw_data_dir,
            self.processed_data_dir,
            self.benchmark_data_dir,
            self.benchmark_cases_dir,
            self.benchmark_outputs_dir,
            self.documents_dir,
            self.vector_store_dir,
            self.investigations_output_dir,
            self.benchmark_output_dir,
            self.reports_output_dir,
        )

        for directory in directories:
            directory.mkdir(
                parents=True,
                exist_ok=True,
            )


# ============================================================================
# SINGLETON SETTINGS
# ============================================================================

@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """
    Return the cached application settings instance.
    """

    return Settings()